const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const packaged=process.env.KRS_CHROMIUM_MODULE?require(process.env.KRS_CHROMIUM_MODULE):null;
 const browser=await chromium.launch({headless:true,...(packaged?{executablePath:await packaged.executablePath(),args:[...packaged.args.filter(x=>!['--single-process','--disable-web-security'].includes(x)&&!x.startsWith('--use-gl=')&&!x.startsWith('--use-angle=')),'--disable-gpu']}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1050}});const errors=[];
 await context.route('**/community-config.json',r=>r.fulfill({json:{enabled:false}}));await context.route('**/firebase-client.js',r=>r.fulfill({contentType:'text/javascript',body:'export async function createFirebaseClient(){return {observe(cb){cb(null)},currentUser(){return null}}}'}));
 await context.route('**/assets/*.mp3',r=>{const b=fs.readFileSync(path.join(__dirname,'../dist/assets',new URL(r.request().url()).pathname.split('/').pop())),m=(r.request().headers().range||'').match(/bytes=(\d+)-(\d*)/),start=m?Number(m[1]):0,end=m&&m[2]?Math.min(Number(m[2]),b.length-1):b.length-1;return r.fulfill({status:m?206:200,headers:{'content-type':'audio/mpeg','accept-ranges':'bytes',...(m?{'content-range':`bytes ${start}-${end}/${b.length}`}:{})},body:b.subarray(start,end+1)});});
 await context.addInitScript(()=>localStorage.setItem('krs-access-seen-v1','1'));const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/');await page.locator('.release-card').nth(3).waitFor();
 assert(await page.locator('#listening-rail').isVisible());assert.equal(await page.locator('.artist-chip').count(),4);assert(!await page.locator('#recent-section').isVisible());
 await page.locator('#rail-play').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('krs-listening-history')||'[]').length===1);await page.locator('#rail-play').click();assert.equal(await page.locator('#recent-list .listening-row').count(),1);
 await page.locator('#discovery-shuffle').click();await page.waitForFunction(()=>document.querySelector('#player-title').textContent!=='Remember'&&document.querySelector('#audio').currentTime>1.1);await page.locator('#rail-play').click();assert.equal(await page.locator('#shuffle').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#recent-list .listening-row').count(),2);
 const current=await page.locator('#player-title').innerText();assert.equal(await page.locator('#rail-title').innerText(),current);
 await page.evaluate(()=>Promise.all(document.getAnimations().map(x=>x.finished)));await page.screenshot({path:'.test-artifacts/KYROSHIX-experiencia-desktop.png'});
 await page.locator('#rail-sound').click();assert(await page.locator('#sound-panel').isVisible());assert(!await page.locator('#now-queue-panel').isVisible());await page.locator('[data-now-queue-tab]').click();assert(await page.locator('#now-queue-panel').isVisible());assert(!await page.locator('#sound-panel').isVisible());
 await page.locator('[data-now-queue-tab]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-now-sound]').getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('[data-now-queue-tab]').getAttribute('aria-selected'),'true');await page.locator('[data-now-close]').click();
 await page.locator('.artist-chip').first().click();await page.waitForFunction(()=>location.pathname==='/musicas');assert.equal(await page.locator('.release-card').count(),1);await page.locator('#clear-search').click();
 await page.goto('http://127.0.0.1:8765/#recentes');await page.locator('.release-card').nth(1).waitFor();assert.equal(await page.locator('.release-card').count(),2);assert(await page.locator('#history-tools').isVisible());await page.reload();assert.equal(await page.locator('.release-card').count(),2);
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:8765/');await page.locator('.release-card').nth(3).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page overflow '+width);await page.locator('#player-cover').click();assert(await page.locator('#music-player').evaluate(x=>x.scrollWidth<=x.clientWidth),'player overflow '+width);await page.locator('[data-now-sound]').click();assert(await page.locator('#music-player').evaluate(x=>x.scrollWidth<=x.clientWidth),'sound overflow '+width);await page.locator('[data-now-close]').click();}
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8765/');await page.locator('.release-card').nth(3).waitFor();assert(await page.locator('.mobile-nav').isVisible());assert(!await page.locator('#listening-rail').isVisible());const nav=await page.locator('.mobile-nav').boundingBox(),dock=await page.locator('.player').boundingBox();assert(dock.y+dock.height<=nav.y,'dock obscures navigation');await page.evaluate(()=>Promise.all(document.getAnimations().map(x=>x.finished)));await page.screenshot({path:'.test-artifacts/KYROSHIX-experiencia-celular.png'});
 await page.locator('#player-cover').click();await page.locator('[data-now-queue-tab]').click();await page.evaluate(()=>Promise.all(document.getAnimations().map(x=>x.finished)));await page.screenshot({path:'.test-artifacts/KYROSHIX-player-compacto.png'});assert(await page.locator('#music-player').evaluate(x=>x.scrollHeight<1000),'player unnecessarily tall');await page.locator('[data-now-sound]').click();await page.locator('#sound-enabled').check();await page.locator('#sound-preset').selectOption('nightcore');await page.locator('#sound-panel').scrollIntoViewIfNeeded();await page.evaluate(()=>Promise.all(document.getAnimations().map(x=>x.finished)));await page.screenshot({path:'.test-artifacts/KYROSHIX-som-organizado.png'});
 await page.locator('[data-now-close]').click();await page.goto('http://127.0.0.1:8765/#recentes');await page.locator('#history-clear').click();await page.locator('#confirm-yes').click();assert.equal(await page.locator('.release-card').count(),0);assert(await page.locator('#empty-state').isVisible());await page.route('**/catalog-seed.js',async route=>{const response=await route.fetch(),source=await response.text();await route.fulfill({response,body:source.replace("title:'Remember'","title:'"+'NewJeans GODS League of Legends Worlds Anthem KYROSHIX RELEASES NIGHTCORE REMIX '.repeat(3)+"'")});});await page.goto('http://127.0.0.1:8765/');await page.locator('#player-cover').click();const titleMore=page.locator('[data-now-title-more]');assert((await page.locator('#now-title').innerText()).length>90);{assert(await titleMore.isVisible());await titleMore.click();assert.equal(await titleMore.getAttribute('aria-expanded'),'true');assert(await page.locator('#music-player').evaluate(x=>x.scrollWidth<=x.clientWidth));}assert.deepEqual(errors,[]);await browser.close();console.log('PASS: live listening rail, local history/persistence/clear, artist discovery, shuffle, keyboard panels, layouts 360–1440, mobile navigation and compact player.');
})().catch(e=>{console.error(e);process.exit(1)});
