const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{
 const packaged=process.env.KRS_CHROMIUM_MODULE?require(process.env.KRS_CHROMIUM_MODULE):null,browser=await chromium.launch({headless:true,...(packaged?{executablePath:await packaged.executablePath(),args:packaged.args.filter(x=>!['--single-process','--disable-web-security'].includes(x))}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const fake=`export async function createFirebaseClient(){let user=null,verified=false;const callbacks=[];const emit=u=>{user=u;verified=false;callbacks.forEach(cb=>cb(u));};return{providers:['google.com','github.com'],requiresCode:true,observe(cb){callbacks.push(cb);queueMicrotask(()=>cb(user));return()=>{}},currentUser(){return user},token(){return Promise.resolve(user?(verified?user.uid+'-verified':'pending'):null)},async google(){emit({uid:'owner',displayName:'KYROSHIX',email:'owner@example.test',emailVerified:true});return{user}},async oauth(){emit({uid:'viewer',displayName:'Ouvinte',email:'viewer@example.test',emailVerified:true});return{user}},async login(){return this.google()},async logout(){emit(null)},async codeStatus(){return{verified}},async sendCode(){return{challenge:'test',destination:'ow•••@example.test'}},async confirmCode(id,code){if(code!=='123456')throw{publicMessage:'Código incorreto.'};verified=true;return{verified}},async linkProvider(){return{user}},async refresh(){return user}}}`;
 await context.route('**/firebase-client.js',r=>r.fulfill({contentType:'text/javascript',body:fake}));
 await context.route('**/community-config.json',r=>r.fulfill({json:{enabled:true,supabaseUrl:'https://platform-test.supabase.co',publishableKey:'test-key'}}));
 const seed=(await import('../dist/catalog-seed.js')).seedTracks.map(x=>({...x,kind:'audio',channel_uid:'owner'}));
 let videos=[{id:'video-one',kind:'video',title:'Uma nova frequência',artists:'KYROSHIX',description:'Vídeo de teste',credits:'Teste local',duration:8,video_source:'webm',video_url:'https://media.test/video.webm',cover_path:'',channel_uid:'owner',chapters:[{start:0,title:'Início'},{start:3,title:'Capítulo dois'}],drm_system:'none',caption_url:'',published:true,created_at:'2026-10-03T00:00:00Z'}];
 const profiles={owner:{uid:'owner',display_name:'KYROSHIX',handle:'kyroshix',bio:'Música e comunidade.',links:[],avatar_path:'',banner_path:'',accent:'#ff4059'},viewer:{uid:'viewer',display_name:'Ouvinte',handle:'ouvinte',links:[],avatar_path:'',banner_path:'',accent:'#ff4059'}};
 const reactions={},subscriptions=new Set();let uploads=[];
 await context.route('https://media.test/**',r=>{const bytes=fs.readFileSync(path.join(__dirname,'fixtures/sample.webm')),range=r.request().headers().range?.match(/^bytes=(\d+)-(\d*)$/),start=range?Number(range[1]):0,end=range?.[2]?Number(range[2]):bytes.length-1;return r.fulfill({status:range?206:200,contentType:'video/webm',body:bytes.subarray(start,end+1),headers:{'access-control-allow-origin':'*','accept-ranges':'bytes','content-length':String(end-start+1),...(range?{'content-range':`bytes ${start}-${end}/${bytes.length}`}:{})}});});
 await context.route('https://platform-test.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),p=url.pathname,body=req.postData(),json=body&&req.headers()['content-type']?.includes('application/json')?JSON.parse(body):{},uid=req.headers().authorization?.replace('Bearer ','').replace('-verified',''),verified=req.headers().authorization?.endsWith('-verified');let data=null;
  if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,DELETE'}});
  if(p==='/rest/v1/krs_tracks'){let rows=url.searchParams.has('kind')?videos:[...seed,...videos];if(url.searchParams.has('id'))rows=rows.filter(x=>x.id===url.searchParams.get('id').slice(3));if(url.searchParams.has('channel_uid'))rows=rows.filter(x=>x.channel_uid===url.searchParams.get('channel_uid').slice(3));data=rows.filter(x=>x.published!==false||verified&&uid==='owner');}
  else if(p==='/rest/v1/krs_profiles'){data=Object.values(profiles);if(url.searchParams.has('uid'))data=data.filter(x=>x.uid===url.searchParams.get('uid').slice(3));if(url.searchParams.has('handle'))data=data.filter(x=>x.handle===url.searchParams.get('handle').slice(3));}
  else if(p==='/rest/v1/krs_comments')data=[];
  else if(p.endsWith('/rpc/krs_is_owner'))data=!!verified&&uid==='owner';
  else if(p.endsWith('/rpc/krs_social')){const mine=reactions[uid]||[];data={counts:Object.values(reactions).flat().reduce((a,v)=>(a[v]=(a[v]||0)+1,a),{}),mine:verified?mine:[],subscribers:subscriptions.size,subscribed:verified&&subscriptions.has(uid)};}
  else if(p.endsWith('/rpc/krs_react')){assert(verified);const own=new Set(reactions[uid]||[]);json.p_active?own.add(json.p_reaction):own.delete(json.p_reaction);reactions[uid]=[...own];}
  else if(p.endsWith('/rpc/krs_subscribe')){assert(verified);json.p_active?subscriptions.add(uid):subscriptions.delete(uid);}
  else if(p.endsWith('/rpc/krs_my_subscriptions'))data=subscriptions.has(uid)?[profiles.owner]:[];
  else if(p.endsWith('/rpc/krs_save_channel')){assert(verified);Object.assign(profiles[uid],{handle:json.p_handle,links:json.p_links});data=profiles[uid];}
  else if(p.endsWith('/rpc/krs_save_video')){assert(verified&&uid==='owner');const old=videos.findIndex(v=>v.id===json.p_video.id);data={...json.p_video,kind:'video',channel_uid:'owner',created_at:new Date().toISOString()};if(old<0)videos.push(data);else videos[old]=data;}
  else if(p.endsWith('/rpc/krs_delete_track')){assert(verified&&uid==='owner');videos=videos.filter(v=>v.id!==json.p_id);}
  else if(p.startsWith('/storage/v1/object/kyroshix-')){assert(verified&&uid==='owner');uploads.push(p);data={Key:p};}
  else if(p==='/storage/v1/object/kyroshix-video'||p==='/storage/v1/object/kyroshix-media')data=[];
  else throw Error('Unexpected endpoint '+p);
  await route.fulfill({json:data,headers:{'access-control-allow-origin':'*'}});
 });
 await page.goto('http://127.0.0.1:8765/');await page.locator('.release-card').nth(3).waitFor();
 await page.goto('http://127.0.0.1:8765/#videos');await page.locator('.video-card').waitFor();if(await page.locator('#search-toggle').isVisible())await page.locator('#search-toggle').click();await page.locator('#search').fill('nova');await page.locator('.video-card').waitFor();assert.equal(await page.locator('.video-card').count(),1);await page.locator('#clear-search').click();
 await page.locator('.video-thumbnail').click();await page.locator('.cinema-player video').waitFor();await page.locator('.video-center').click();await page.waitForFunction(()=>document.querySelector('.cinema-player video')?.currentTime>0);await page.locator('[data-speed]').selectOption('1.5');assert.equal(await page.locator('.cinema-player video').evaluate(v=>v.playbackRate),1.5);await page.locator('.video-control-row [data-vplay]').click();await page.locator('[data-chapter="3"]').click();await page.waitForFunction(()=>document.querySelector('.cinema-player video')?.currentTime>=3);await page.locator('[data-theater]').click();assert(await page.locator('.watch-layout').evaluate(x=>x.classList.contains('theater')));
 for(const width of [360,390]){await page.setViewportSize({width,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)){await page.screenshot({path:'.test-artifacts/watch-overflow.png'});console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1}).map(e=>({tag:e.tagName,cls:e.className,w:e.getBoundingClientRect().width,r:e.getBoundingClientRect().right})).slice(0,25)));throw Error('Watch overflow '+width);}}
 await page.screenshot({path:'.test-artifacts/KYROSHIX-watch-mobile.png'});await page.setViewportSize({width:1440,height:1000});
 await page.locator('#account-open').click();await page.locator('#auth-google').click();await page.locator('#auth-code-panel').waitFor();assert.equal(await page.locator('#auth-profile').isVisible(),false);await page.locator('#auth-code-send').click();await page.locator('#auth-code').fill('000000');await page.locator('#auth-code-confirm').click();await page.waitForFunction(()=>document.querySelector('#auth-message').textContent.includes('incorreto'));await page.locator('#auth-code').fill('123456');await page.locator('#auth-code-confirm').click();await page.locator('#auth-profile').waitFor();await page.locator('#account-dialog .dialog-close').click();
 await page.goto('http://127.0.0.1:8765/#studio');await page.locator('[data-new-video]').waitFor();await page.locator('[data-new-video]').click();await page.locator('#video-title-input').fill('Novo vídeo');await page.locator('#video-file-input').setInputFiles(path.join(__dirname,'fixtures/sample.webm'));await page.locator('#video-editor summary').click();await page.locator('#video-chapters-input').fill('0:00 Início\n0:03 Segundo capítulo');await page.locator('#video-save').click();await page.locator('#video-editor').waitFor({state:'hidden'});assert.equal(videos.length,2);assert(uploads.some(u=>u.includes('kyroshix-video/')));
 const created=videos.find(x=>x.title==='Novo vídeo');await page.locator(`[data-edit-video="${created.id}"]`).click();await page.locator('#video-title-input').fill('Vídeo atualizado');await page.locator('#video-save').click();await page.locator('#video-editor').waitFor({state:'hidden'});assert(videos.some(v=>v.title==='Vídeo atualizado'));
 await page.goto('http://127.0.0.1:8765/#perfil');await page.locator('[data-channel-edit]').click();await page.locator('#channel-handle').fill('kyroshix_corp');await page.locator('#channel-links').fill('YouTube | https://youtube.com/@kyroshixcorp');await page.locator('#channel-form .primary').click();await page.locator('.channel-title h1').waitFor();assert.equal(profiles.owner.handle,'kyroshix_corp');
 await page.locator('#account-open').click();await page.locator('#auth-signout').click();await page.locator('[data-provider="github.com"]').click();await page.locator('#auth-code-panel').waitFor();await page.locator('#auth-code-send').click();await page.locator('#auth-code').fill('123456');await page.locator('#auth-code-confirm').click();await page.locator('#auth-profile').waitFor();await page.locator('#account-dialog .dialog-close').click();await page.goto('http://127.0.0.1:8765/#canal/kyroshix_corp');await page.locator('[data-subscribe]').click();await page.waitForFunction(()=>document.querySelector('[data-subscribe]')?.getAttribute('aria-pressed')==='true');assert(subscriptions.has('viewer'));
 await page.goto('http://127.0.0.1:8765/#assistir/video-one');await page.locator('[data-reaction="like"]').click();await page.waitForFunction(()=>document.querySelector('[data-reaction="like"]')?.getAttribute('aria-pressed')==='true');assert(reactions.viewer.includes('like'));await page.goto('http://127.0.0.1:8765/#inscricoes');await page.locator('.subscription-card').waitFor();await page.goto('http://127.0.0.1:8765/#studio');assert.equal(await page.locator('#studio-content').isVisible(),false);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: real video playback, speed/chapters/theater/mobile, mandatory-code UI, code error/retry, owner video upload/edit, channel/links, alternate OAuth, subscription/reaction persistence and non-owner gating. Auth and backend responses simulated.');
})().catch(e=>{console.error(e);process.exit(1)});
