const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
const {PGlite}=require(process.env.KRS_TEST_NODE_MODULES?path.join(process.env.KRS_TEST_NODE_MODULES,'@electric-sql/pglite'):'@electric-sql/pglite');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create schema storage;
 create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,unique(bucket_id,name));
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated;
 grant select,insert,update,delete on storage.objects to anon,authenticated;`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../backend/01-instalar.sql'),'utf8'));
 await db.exec("insert into krs_private.owners values ('owner');");
 const claim=(uid,verified=true,project='kyroshix-releases')=>({sub:uid,email_verified:verified,iss:`https://securetoken.google.com/${project}`,aud:project});
 async function as(c){await db.exec('reset role; set role anon;');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify(c||{})]);}
 async function scalar(sql,args=[]){return (await db.query(sql,args)).rows[0];}
 async function denied(sql,args=[]){await assert.rejects(()=>db.query(sql,args));}
 const profile={display_name:'Alice <script>',bio:'Hello'};
 await as(null);assert.equal((await db.query('select * from public.krs_tracks')).rows.length,4);
 await denied('select * from krs_private.owners');await denied('insert into krs_private.owners values ($1)',['intruder']);
 await denied('select public.krs_save_profile($1)',[JSON.stringify(profile)]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/avatar.webp',{mimetype:'image/webp',contentLength:1000}]);
 await as(claim('alice',false));await denied('select public.krs_save_profile($1)',[JSON.stringify(profile)]);
 await as(claim('owner',true,'foreign-project'));assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,false);
 await as(claim('alice'));await db.query('select public.krs_save_profile($1)',[JSON.stringify(profile)]);
 await denied('update public.krs_profiles set uid=$1',['owner']);
 await denied('select public.krs_save_profile($1)',[JSON.stringify({...profile,avatar_path:'profiles/bob/avatar.webp'})]);
 await db.query('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/avatar.webp',{mimetype:'image/webp',size:10000}]);
 // Storage permission preflight uses contentLength, not the persisted size field.
 // Exercise both a new image and overwriting an existing image under real RLS.
 await db.exec('begin');
 for(const name of ['profiles/alice/avatar.webp','profiles/alice/banner.webp']){
  await db.query('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3) on conflict(bucket_id,name) do update set metadata=excluded.metadata',['kyroshix-media',name,{mimetype:'image/webp',contentLength:12000}]);
 }
 await db.exec('rollback');
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/banner.webp',{mimetype:'image/webp',contentLength:2097153}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/banner.webp',{mimetype:'image/webp'}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/bob/banner.webp',{mimetype:'image/webp',contentLength:1000}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/bob/avatar.webp',{mimetype:'image/webp',size:1000}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/banner.webp',{mimetype:'audio/mpeg',size:1000}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/banner.webp',{mimetype:'image/webp',size:3000000}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','tracks/evil/audio.mp3',{mimetype:'audio/mpeg',size:1000}]);
 await denied('select public.krs_save_track($1)',[JSON.stringify({id:'intruder'})]);
 await denied('select public.krs_delete_track($1)',['remember']);
 const comment=(await scalar('select to_jsonb(public.krs_comment($1,$2,null)) as c',['remember','Minha música favorita'])).c;
 await denied('select public.krs_comment($1,$2,null)',['remember','Spam imediato']);
 await as(claim('bob'));await db.query('select public.krs_save_profile($1)',[{display_name:'Bob'}]);
 await denied('select public.krs_edit_comment($1,$2)',[comment.id,'Hijack']);
 await denied('select public.krs_delete_comment($1)',[comment.id]);
 await denied('select public.krs_comment($1,$2,$3)',['darkness','Wrong track reply',comment.id]);
 const reply=(await scalar('select to_jsonb(public.krs_comment($1,$2,$3)) as c',['remember','Também gostei',comment.id])).c;
 await as(claim('alice'));await db.query('select public.krs_edit_comment($1,$2)',[comment.id,'Meu comentário editado']);
 await as(claim('owner'));assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,true);
 await db.query('select public.krs_delete_comment($1)',[comment.id]);
 assert.equal((await scalar('select deleted from public.krs_comments where id=$1',[comment.id])).deleted,true);
 assert.equal((await scalar('select body from public.krs_comments where id=$1',[reply.id])).body,'Também gostei');
 const track={id:'test-music',title:'New track',artists:'Artist',remix:'Remix',tags:['remix'],audio_path:'tracks/test-music/audio.mp3',cover_path:'',duration:60};
 await denied('select public.krs_save_track($1)',[track]);
 await db.query('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media',track.audio_path,{mimetype:'audio/mpeg',size:1000}]);
 await db.query('select public.krs_save_track($1)',[track]);
 await db.query('select public.krs_save_track($1)',[{...track,title:'Updated title'}]);
 assert.equal((await scalar('select title from public.krs_tracks where id=$1',[track.id])).title,'Updated title');
 await db.query('select public.krs_delete_track($1)',[track.id]);
 assert.equal((await db.query('select * from public.krs_tracks where id=$1',[track.id])).rows.length,0);
 await db.query('select public.krs_delete_track($1)',['remember']);
 assert.equal((await db.query('select * from public.krs_comments where track_id=$1',['remember'])).rows.length,0);
 await as(null);assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,false);
 await db.exec('reset role');
 await db.query('insert into krs_private.owners values ($1)',['wcJXpZgLs8YMLZ3F2JAGk1TWVl12']);
 const fix=fs.readFileSync(path.join(__dirname,'../backend/03-corrigir-envios-e-dono.sql'),'utf8');
 await db.exec(fix);await db.exec(fix);
 await as(claim('wcJXpZgLs8YMLZ3F2JAGk1TWVl12'));assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,false);
 await as(claim('8Q7S8FgBZjTrg4Mkf46ntcYvl0Q2'));assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,true);
 await as(claim('owner'));assert.equal((await scalar('select public.krs_is_owner() as owner')).owner,true);
 assert.equal((await db.query('select * from public.krs_tracks where id=$1',['remember'])).rows.length,0);
 assert.equal((await db.query('select * from public.krs_profiles where uid=$1',['alice'])).rows.length,1);
 console.log('PASS: upload preflight contentLength for new/replaced profile images; size/type/path restrictions; repeatable owner replacement preserves unrelated accounts and existing content.');
 console.log('PASS: SQL installed; read-only guests; verified Firebase project binding; private owner table; owner-only track create/edit/delete; profile ownership; scoped/type/size-limited uploads; comment ownership, replies, moderation and rate limit.');
 console.log('PGlite executes PostgreSQL/RLS. Firebase JWT signature verification and hosted Storage gateway still require a live Supabase project.');

 await db.exec('reset role');
 for(const name of ['04-plataforma.sql','05-canais-e-reacoes.sql','06-videos.sql','07-codigos-de-acesso.sql'])await db.exec(fs.readFileSync(path.join(__dirname,'../backend/',name),'utf8'));
 await as(claim('alice'));await db.query('select public.krs_save_channel($1,$2)',['alice_music',[{label:'Site',url:'https://example.com/'}]]);
 await denied('select public.krs_save_channel($1,$2)',['alice_music',[{label:'Unsafe',url:'javascript:alert(1)'}]]);
 await as(claim('bob'));await denied('select public.krs_save_channel($1,$2)',['alice_music',[]]);
 await as(claim('owner'));await db.query('select public.krs_save_profile($1)',[{display_name:'Creator'}]);
 const video={id:'video-test',title:'Video',artists:'Creator',video_source:'mp4',video_url:'https://example.com/video.mp4',published:true};
 await db.query('select public.krs_save_video($1)',[video]);
 await db.query('select public.krs_save_video($1)',[{...video,id:'video-draft',published:false}]);
 await denied('select public.krs_save_video($1)',[{...video,video_url:'javascript:alert(1)'}]);
 await denied('select public.krs_save_video($1)',[{...video,drm_system:'widevine'}]);
 await as(claim('alice'));await denied('select public.krs_save_video($1)',[video]);
 await denied('select public.krs_comment($1,$2,null)',['video-draft','hidden']);
 await db.query('select public.krs_react($1,$2,true)',['video-test','like']);await db.query('select public.krs_react($1,$2,true)',['video-test','like']);
 await db.query('select public.krs_subscribe($1,true)',['owner']);
 const social=(await scalar('select public.krs_social($1,$2) as result',['video-test','owner'])).result;
 assert.equal(social.counts.like,1);assert.equal(social.subscribed,true);assert.equal(social.subscribers,1);
 await denied('select * from public.krs_subscriptions');
 await as(null);assert.equal((await db.query("select * from public.krs_tracks where kind='video'")).rows.length,1);
 await denied('select public.krs_react($1,$2,true)',['video-test','like']);
 assert.equal((await scalar('select public.krs_social($1,$2) as result',['video-test','owner'])).result.mine.length,0);
 await denied('select public.krs_email_code_start($1,$2,$3)',['alice',1700000000,'a'.repeat(64)]);

 await db.exec('reset role');
 for(let i=0;i<2;i++)await db.exec(fs.readFileSync(path.join(__dirname,'../backend/09-media-upgrade.sql'),'utf8'));
 assert.equal(Number((await scalar("select file_size_limit from storage.buckets where id='kyroshix-media'")).file_size_limit),52428800);
 await as(claim('alice'));
 await db.query('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3) on conflict(bucket_id,name) do update set metadata=excluded.metadata',['kyroshix-media','profiles/alice/avatar.webp',{mimetype:'image/webp',contentLength:8388608}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/alice/banner.webp',{mimetype:'image/webp',contentLength:8388609}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','profiles/bob/banner.webp',{mimetype:'image/webp',contentLength:8388608}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','tracks/test-music/original.flac',{mimetype:'audio/flac',contentLength:52428800}]);
 await as(claim('owner'));
 for(const [ext,mimetype] of Object.entries({mp3:'audio/mpeg',flac:'audio/flac',wav:'audio/wav',m4a:'audio/mp4',ogg:'audio/ogg'})){
  const name='tracks/test-music/original.'+ext;
  await db.query('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media',name,{mimetype,contentLength:52428800}]);
  await db.query('select public.krs_save_track($1)',[{...track,audio_path:name,byte_size:52428800}]);
 }
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','tracks/test-music/large.wav',{mimetype:'audio/wav',contentLength:52428801}]);
 await denied('insert into storage.objects(bucket_id,name,metadata) values ($1,$2,$3)',['kyroshix-media','tracks/test-music/fake.flac',{mimetype:'text/html',contentLength:1000}]);
 await denied('select public.krs_save_track($1)',[{...track,byte_size:52428801}]);
 await denied('select public.krs_save_track($1)',[{...track,id:'video-test'}]);
 console.log('PASS: additive/repeated media migration, own profile 8 MiB limit, 50 MiB audio and MIME checks, FLAC/WAV/M4A/OGG saves, owner authorization and video isolation.');
 await db.exec('reset role; update krs_private.login_policy set require_code=true;');
 await as({...claim('alice'),auth_time:1700000000});assert.equal((await scalar('select public.krs_uid() as uid')).uid,null);
 await db.exec('reset role;set role service_role;');
 const challenge=(await scalar('select public.krs_email_code_start($1,$2,$3) as id',['alice',1700000000,'a'.repeat(64)])).id;
 await denied('select public.krs_email_code_start($1,$2,$3)',['alice',1700000000,'b'.repeat(64)]);
 assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['bob',1700000000,challenge,'a'.repeat(64)])).ok,false);
 for(let i=0;i<4;i++)assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['alice',1700000000,challenge,'b'.repeat(64)])).ok,false);
 assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['alice',1700000000,challenge,'a'.repeat(64)])).ok,true);
 assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['alice',1700000000,challenge,'a'.repeat(64)])).ok,false);
 await as({...claim('alice'),auth_time:1700000000});assert.equal((await scalar('select public.krs_uid() as uid')).uid,'alice');
 await as({...claim('alice'),auth_time:1700000001});assert.equal((await scalar('select public.krs_uid() as uid')).uid,null);
 await db.exec('reset role;set role service_role;');
 const expired=(await scalar('select public.krs_email_code_start($1,$2,$3) as id',['expired-user',1700000000,'a'.repeat(64)])).id;
 await db.exec('reset role');await db.query("update krs_private.login_challenges set expires_at=now()-interval '1 second' where id=$1",[expired]);await db.exec('set role service_role');
 assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['expired-user',1700000000,expired,'a'.repeat(64)])).ok,false);
 const locked=(await scalar('select public.krs_email_code_start($1,$2,$3) as id',['locked-user',1700000000,'a'.repeat(64)])).id;
 for(let i=0;i<5;i++)assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['locked-user',1700000000,locked,'b'.repeat(64)])).ok,false);
 assert.equal((await scalar('select public.krs_email_code_check($1,$2,$3,$4) as ok',['locked-user',1700000000,locked,'a'.repeat(64)])).ok,false);
 await as({...claim('phone-user',false),phone_number:'+5511999999999',firebase:{sign_in_provider:'phone'}});assert.equal((await scalar('select public.krs_uid() as uid')).uid,'phone-user');
 console.log('PASS: video ownership/draft visibility, channel handles/links, idempotent reactions/subscriptions, private follow lists, service-only OTP operations, retry/rate controls, single-use codes and session-bound server enforcement.');
 await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
