const {chromium}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs');const packaged=require(process.env.KRS_CHROMIUM_MODULE);const errors=[];
function tone(hz=440,seconds=10){const rate=22050,count=rate*seconds,b=Buffer.alloc(44+count*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)b.writeInt16LE(Math.round(5000*Math.sin(i/rate*Math.PI*2*hz)),44+i*2);return b;}
(async()=>{
 const browser=await chromium.launch({executablePath:await packaged.executablePath(),args:packaged.args.filter(x=>!['--single-process','--disable-web-security'].includes(x))});
 const context=await browser.newContext({viewport:{width:1440,height:1050}});await context.route('**/community-config.json',r=>r.fulfill({json:{enabled:false}}));await context.route('**/firebase-client.js',r=>r.fulfill({contentType:'text/javascript',body:'export async function createFirebaseClient(){return {observe(cb){cb(null)},currentUser(){return null}}}'}));
 await context.route('**/assets/*.mp3',r=>{const b=tone(r.request().url().includes('remember')?440:880),m=(r.request().headers().range||'').match(/bytes=(\d+)-(\d*)/),start=m?Number(m[1]):0,end=m&&m[2]?Math.min(Number(m[2]),b.length-1):b.length-1;return r.fulfill({status:m?206:200,headers:{'content-type':'audio/wav','accept-ranges':'bytes',...(m?{'content-range':`bytes ${start}-${end}/${b.length}`}:{})},body:b.subarray(start,end+1)});});
 await context.addInitScript(()=>localStorage.setItem('krs-access-seen-v1','1'));const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/');await page.locator('.release-card').nth(3).waitFor();
 await page.locator('#player-cover').click();await page.locator('[data-now-sound]').click();assert.equal(await page.locator('#sound-crossfade').inputValue(),'4');
 await page.locator('#sound-crossfade').fill('2');await page.locator('#sound-enabled').check();await page.locator('#sound-preset').selectOption('electronic');await page.locator('#sound-bass').fill('2');await page.locator('#eq-3').fill('1.5');assert.equal(await page.locator('#sound-preset').inputValue(),'custom');
 await page.locator('[data-now-play]').click();await page.waitForFunction(()=>!document.querySelector('#audio').paused&&document.querySelector('#audio').currentTime>.1);
 await page.locator('#now-seek').fill('8.1');await page.waitForFunction(()=>document.querySelectorAll('audio:not([data-unused])').length===2&&[...document.querySelectorAll('audio')].every(a=>!a.paused),{},{timeout:6000});await page.waitForFunction(()=>document.querySelector('#now-title').textContent==='Legends Never Die');await page.waitForFunction(()=>document.querySelector('#audio-next').paused,{},{timeout:5000});
 assert(await page.locator('#audio').evaluate(a=>a.currentTime>1.7));await page.locator('#now-transition').waitFor({state:'hidden'});
 // A manual transition can be paused without leaving a hidden track playing.
 await page.locator('[data-now-next]').click();await page.waitForFunction(()=>[...document.querySelectorAll('audio')].every(a=>!a.paused));await page.locator('[data-now-play]').click();assert(await page.evaluate(()=>[...document.querySelectorAll('audio')].every(a=>a.paused)));
 // Seeking during a transition stops its outgoing deck; playback speed remains effective.
 await page.locator('[data-now-play]').click();await page.locator('[data-now-next]').click();await page.waitForFunction(()=>[...document.querySelectorAll('audio')].every(a=>!a.paused));await page.locator('#now-seek').fill('3');assert(await page.locator('#audio-next').evaluate(a=>a.paused));await page.locator('#now-speed').selectOption('1.25');assert.equal(await page.locator('#audio').evaluate(a=>a.playbackRate),1.25);await page.locator('[data-now-play]').click();
 await page.screenshot({path:'.test-artifacts/KYROSHIX-som.png'});await page.setViewportSize({width:390,height:844});assert(await page.locator('#music-player').evaluate(el=>el.scrollWidth<=el.clientWidth));await page.locator('#sound-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'.test-artifacts/KYROSHIX-som-celular.png'});
 await page.reload();await page.locator('#player-cover').click();await page.locator('[data-now-sound]').click();assert.equal(await page.locator('#sound-crossfade').inputValue(),'2');assert.equal(await page.locator('#eq-3').inputValue(),'1.5');assert(await page.locator('#sound-enabled').isChecked());
 await page.locator('#sound-reset').click();assert(!await page.locator('#sound-enabled').isChecked());assert.equal(await page.locator('#sound-crossfade').inputValue(),'2');
 // Repeat-one disables the automatic transition, even near the end.
 await page.locator('[data-now-repeat]').click();await page.locator('[data-now-play]').click();await page.waitForFunction(()=>document.querySelector('#audio').readyState>=2);await page.locator('#now-seek').fill('9.3');await page.waitForFunction(()=>document.querySelector('#audio').currentTime<2,{},{timeout:4000});assert.equal(await page.locator('#now-title').innerText(),'Remember');assert(await page.locator('#audio-next').evaluate(a=>a.paused));await page.locator('[data-now-play]').click();await page.locator('[data-now-repeat]').click();
 // Zero seconds removes overlap, rather than leaving a silent extra deck running.
 await page.locator('#sound-crossfade').fill('0');await page.locator('[data-now-play]').click();await page.locator('[data-now-next]').click();assert(await page.locator('#audio-next').evaluate(a=>a.paused));await page.locator('[data-now-play]').click();
 // Offline rendering proves the EQ changes signal and bypass preserves the original.
 const dsp=await page.evaluate(async()=>{const {createSoundGraph,defaults,fadeCurves,sanitizeSettings}=await import('./audio-engine.js');async function rms(hz,enabled){const ctx=new OfflineAudioContext(1,48000,48000),s={...defaults(),enabled,peaks:false,bands:[-12,0,0,0,0,0]},g=createSoundGraph(ctx,s,1),o=ctx.createOscillator();o.frequency.value=hz;o.connect(g.mix);o.start();const data=(await ctx.startRendering()).getChannelData(0);return Math.sqrt(data.slice(12000).reduce((a,v)=>a+v*v,0)/(data.length-12000));}const curve=fadeCurves();return {dry:await rms(40,false),wet:await rms(40,true),peakSum:Math.max(...curve.incoming.map((v,i)=>v+curve.outgoing[i])),safe:sanitizeSettings({crossfade:999,bands:[Infinity,999,-999],bass:999}).bands};});assert(Math.abs(dsp.dry-Math.SQRT1_2)<.01);assert(dsp.wet<dsp.dry*.5);assert(dsp.peakSum<=1.00001);assert.deepEqual(dsp.safe,[0,12,-12,0,0,0]);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: audible-deck overlap and completion, pause/seek cancellation, speed, repeat-one, crossfade off, saved EQ/preset/reset, responsive panel, offline EQ response/bypass and bounded crossfade gain.');
})().catch(e=>{console.error(e);process.exit(1)});
